// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtOEu9tjZnKs7_4iSk6wJ8ysplMl5xIk',
    appId: '1:1057723034001:web:a15d7f7f2933791dead230',
    messagingSenderId: '1057723034001',
    projectId: 'starter-58bed',
    authDomain: 'starter-58bed.firebaseapp.com',
    storageBucket: 'starter-58bed.appspot.com',
    measurementId: 'G-8K37MTPJ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkHhin4G5Ahf_1MzooFchlLyg9OIbRYbo',
    appId: '1:1057723034001:android:928155134ac4a00fead230',
    messagingSenderId: '1057723034001',
    projectId: 'starter-58bed',
    storageBucket: 'starter-58bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2884D79DeAfNipBamQtMMAj96y5FbiB0',
    appId: '1:1057723034001:ios:3eed4720d223ebe1ead230',
    messagingSenderId: '1057723034001',
    projectId: 'starter-58bed',
    storageBucket: 'starter-58bed.appspot.com',
    iosClientId: '1057723034001-e7glqkljatn18akps6pbg98n86h8jsof.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnflutter',
  );
}
